# Generated by Django 4.0.4 on 2022-04-30 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 4, 29, 21, 2, 30, 664838)),
        ),
    ]
